language: python

python:
    - "2.7"

before_install:
    - wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda
    - conda info -a
    - conda create -q -n r anaconda
    - source activate r


install:
    - conda install --yes python=$TRAVIS_PYTHON_VERSION numpy scipy
    - conda install --yes -c r r
    - conda install --yes -c https://conda.anaconda.org/r rpy2
    - conda install --yes -c https://conda.anaconda.org/r r-testthat
    - wget https://cran.r-project.org/src/contrib/Rcpp_0.12.2.tar.gz
    - R CMD INSTALL Rcpp_0.12.2.tar.gz
    - wget https://cran.r-project.org/src/contrib/plyr_1.8.3.tar.gz
    - R CMD INSTALL plyr_1.8.3.tar.gz
    - wget https://cran.r-project.org/src/contrib/digest_0.6.8.tar.gz
    - R CMD INSTALL digest_0.6.8.tar.gz
    - wget https://cran.r-project.org/src/contrib/gtable_0.1.2.tar.gz
    - R CMD INSTALL gtable_0.1.2.tar.gz
    - wget https://cran.r-project.org/src/contrib/magrittr_1.5.tar.gz
    - R CMD INSTALL magrittr_1.5.tar.gz
    - wget https://cran.r-project.org/src/contrib/stringi_1.0-1.tar.gz
    - R CMD INSTALL stringi_1.0-1.tar.gz
    - wget https://cran.r-project.org/src/contrib/stringr_1.0.0.tar.gz
    - R CMD INSTALL stringr_1.0.0.tar.gz
    - wget https://cran.r-project.org/src/contrib/reshape2_1.4.1.tar.gz
    - R CMD INSTALL reshape2_1.4.1.tar.gz
    - wget https://cran.r-project.org/src/contrib/colorspace_1.2-6.tar.gz
    - R CMD INSTALL colorspace_1.2-6.tar.gz
    - wget https://cran.r-project.org/src/contrib/munsell_0.4.2.tar.gz
    - R CMD INSTALL munsell_0.4.2.tar.gz
    - wget https://cran.r-project.org/src/contrib/labeling_0.3.tar.gz
    - R CMD INSTALL labeling_0.3.tar.gz
    - wget https://cran.r-project.org/src/contrib/dichromat_2.0-0.tar.gz
    - R CMD INSTALL dichromat_2.0-0.tar.gz
    - wget https://cran.r-project.org/src/contrib/RColorBrewer_1.1-2.tar.gz
    - R CMD INSTALL RColorBrewer_1.1-2.tar.gz
    - wget https://cran.r-project.org/src/contrib/scales_0.3.0.tar.gz
    - R CMD INSTALL scales_0.3.0.tar.gz
    - wget https://cran.r-project.org/src/contrib/proto_0.3-10.tar.gz
    - R CMD INSTALL proto_0.3-10.tar.gz
    - wget https://cran.r-project.org/src/contrib/ggplot2_1.0.1.tar.gz
    - R CMD INSTALL ggplot2_1.0.1.tar.gz
    - wget https://cran.r-project.org/src/contrib/sciplot_1.1-0.tar.gz
    - R CMD INSTALL sciplot_1.1-0.tar.gz
    - pip install coveralls

script:
    - cd DevelopingRelease/WinnowDevel/
    - path=$PWD
    - cd Tests
    - coverage run --source $path/adjustments.py,$path/checkhidden.py,$path/data.py,$path/fileimport.py,$path/gwas.py,$path/performetrics.py,$path/winnow.py winnowdevel_test_suite.py
    - cd ../../DemonstrateDevel/
    - demopath=$PWD
    - cd Tests
    - coverage run --source $demopath/demonstrate.py demonstratedevel_test_suite.py
    - cd ../..
    - mv DemonstrateDevel/Tests/.coverage .coverage.demonstrate
    - mv WinnowDevel/Tests/.coverage .coverage.winnow
    - coverage combine

after_script:
    - coveralls